set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'wfxr/tmux-power'
set -g @plugin 'wfxr/tmux-net-speed'

set -g @tmux_power_theme 'gold'
set -g @tmux_power_show_upload_speed    true
set -g @tmux_power_show_download_speed  true
set -g @tmux_power_show_web_reachable   true
set -g @tmux_power_upload_speed_icon    '󰕒'
set -g @tmux_power_download_speed_icon  '󰇚'

set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"
set -g allow-passthrough all

# enable copy mode
setw -g mode-keys vi

# custom keybinds
bind 'C-o' switch-client -l
bind 'C-i' rotate-window
bind 'C-m' rotate-window -D
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send-keys -X begin-selection \; send-keys -X rectangle-toggle
bind -T copy-mode-vi S-Enter send-keys -X copy-selection-no-clear
bind-key g popup -E -w 60 -h 15 "tmux list-sessions -F '#{session_name}' | fzf --prompt='Session: ' --height=100% --reverse | xargs -r tmux switch-client -t"

run '~/.config/tmux/tpm/tpm'
